#### Filtrar trailers por género
GET http://localhost:3000/trailers/genero?genero=Drama
Accept: application/json

###

# Buscar trailers por actor
GET http://localhost:3000/trailers/actor?actor=Casey Cott
Accept: application/json

###

# Obtener series con más de X temporadas
GET http://localhost:3000/trailers/temp?minTemporadas=3
Accept: application/json

###

# Crear un nuevo trailer
POST http://localhost:3000/trailers
Content-Type: application/json

{
    "titulo": "Nuevo Trailer",
    "categoria": "Serie",
    "genero": ["Acción", "Aventura"],
    "reparto": ["Actor1" ],
    "resumen": "Este es un trailer de ejemplo",
    "trailer": "https://www.example.com/trailer"
}

###

# Eliminar un trailer
DELETE http://localhost:3000/trailers/672d02d510174c1c61eac565
Accept: application/json
###

# Manejo de error - Trailer no encontrado
GET http://localhost:3000/trailers/672d02d510174c1c61eac565
Accept: application/json
